### ISSUE TITLE
Toast last update: output strange

### ISSUE THREAD

**Issue by jonathanherrmannengel** [TrianguloY/Average-data-usage-widget#14]
Hello, really helpful app. Thanks.

The last update toast has a strange output:

- date is four days in the past (in this case day one of new period if it helps)
- the day value is displayed as negative number

![Screenshot_20220113-194618.png](https://user-images.githubusercontent.com/38504994/149393654-dd214969-4559-4554-98cf-7212261c7451.png)

Yet not really important as widget updates fine...

**Comment by jonathanherrmannengel** [comment]
Forgot to mention: Using F-Droid version.

**Comment by TrianguloY** [comment]
Hi, glad you like the app.

A negative "current usage" happens when your current usage is less than the average one.

For example, for period from 1 to 31, let's imagine you have 10GB. We are now on roughly half the month, so the average usage is more or less 5GB (this is what the top bar in the widget shows).
If the data you spent this month is more than 5GB, the toast will show the day when the average data will match it. For example, if you have spent 7.5GB (3/4 * 10) the toast will show day 23 (3/4 * 31). And if you spent only 2.5GB (1/4 * 10) the toast will show day 7 (1/4 * 31). The number below is the difference from today, which is now 13 so it would be 10 (23-13) in the first case, and -6 (7-13) in the second case.

Yours shows day 9, -4 days, which means that you have spent approximately 30% (9/31) of this month's data (assuming there is no accumulated).


Hope I made myself clear. It is really hard to explain but once you understand it it makes sense, I promise!

**Comment by jonathanherrmannengel** [comment]
Thank you so much! Great explaination...

I misunderstood your in-app description and thought corresponding day = last update day 🙈

Now it all makes sense and I discovered a cool new feature 🙂
